version: 2

updates:

  - package-ecosystem: github-actions

    directory: /

    schedule:

      interval: monthly

    ignore:

      update-types:

        - major

  - package-ecosystem: npm

    directory: /

    schedule:

      interval: monthly

    ignore:

      update-types:

        - major
