name: Publisher

on:

    release:

        types: [ published ]

jobs:

    clean:

        steps:

            - uses: actions/checkout@v3.5.3

    publish:

        runs-on: ubuntu-latest

        steps:

            - uses: actions/setup-node@v3.7.0

              with:

                  node-version: latest

                  registry-url: https://registry.npmjs.org

            - run: npm install

            - run: npm run build

            - run: npm publish --access public

              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
