name: Publisher

on:

  release:

    types: [ published ]

concurrency:

  group: ${{ github.workflow }}-${{ github.ref }}

  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  build:

    runs-on: ubuntu-latest

    needs: clean

    steps:

      - uses: actions/checkout@v3.5.3

      - uses: actions/setup-node@v3.7.0

        with:

          node-version: latest

      - run: npm install

      - run: npm run build

  publish:

    runs-on: ubuntu-latest

    needs: build

    steps:

      - run: npm publish --access public

        env:

          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
