name: Publisher

on:

    release:

        types: [ published ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3.5.3

    - uses: actions/setup-node@v3.7.0

      with:

        node-version: latest
    
    - run: npm install

    - run: npm run build
